Chris/ground collision
Chris33871/tank_squared pull request #16
Opened 2024-11-08 08:45 UTC by Chris33871

Added a working version of gravity for the player
Renamed a couple sprites/functions

2024-11-08 20:50 UTC, Chris33871 commented
Don't merge! I'll do it, I anticipate conflicts after merge NJ's brancg

2024-11-08 21:12 UTC, 3NJDGZ commented
Let bro cook

2024-11-10 11:56 UTC, 3NJDGZ commented on src/core/player.js
applyGravity() {
        this.playerY += 3;
    }

for this, we could have a separate attribute initialised within the player constructor, instead of having just a number. Make it a constant. e.g., 'this.gravity = 3'

2024-11-10 12:02 UTC, 3NJDGZ commented on src/main.js
is it possible to make it so that the player, and bullet positions are updated within the game loop rather than within a separate loop with the ticker? And also when space bar input is checked. Because i feel like the app.ticker.add kind of also acts as another 'game loop' when ultimately there should only be one where everything is updated and checked.

2024-11-10 12:03 UTC, 3NJDGZ requested changes
sewey

2024-11-10 12:05 UTC, 3NJDGZ commented on src/main.js
<img width="636" alt="image" src="https://github.com/user-attachments/assets/90e302ff-1382-4156-b786-1779d3b37b37">

2024-11-10 13:04 UTC, 3NJDGZ commented on src/core/player.js
yeye no need

2024-11-10 13:10 UTC, 3NJDGZ approved these changes
looks good, everything works

2024-11-10 13:11 UTC, merged