Chris/player movement
Chris33871/tank_squared pull request #28
Opened 2024-12-27 11:52 UTC by Chris33871

2025-01-02 13:17 UTC, 3NJDGZ commented on src/core/player.js
> +        let [px, py] = [this.playerBody.getPosition().x, this.playerBody.getPosition().y] // x,y position according to planck
i assume px, py is planckX, and planckY? Change pls

2025-01-02 13:28 UTC, 3NJDGZ commented on src/core/player.js
> +        let [px, py] = [this.playerBody.getPosition().x, this.playerBody.getPosition().y] // x,y position according to planck
our planckx, and corresponding plancky positions for every single object will probably need to be adapted (i have not implemented it yet though, everything should be relative to the ground as you said before):
```js
var PixelsPerMeter = 50;					// How many pixels represent 1 meter.
var MetersPerPixel = 1/PixelsPerMeter;		// And the reverse.
``` 
this code is from here: https://github.com/dacatchman/pixi-planckjs-demo/blob/master/src/index.html

2025-01-02 13:30 UTC, 3NJDGZ commented on src/core/player.js
> +        this.springBack = this.world.createJoint(
I assume these are for the wheels?

2025-01-02 13:40 UTC, 3NJDGZ commented on src/core/player.js
> +        this.springBack = this.world.createJoint(
what is this for? does this just allow the wheel object to 'spin' for movement? does it also act as some sort of suspension ('dampingRatio', and 'frequencyHz')?

2025-01-02 13:41 UTC, 3NJDGZ commented on src/core/player.js
>          const playerSprite = Sprite.from(this.playerTexture);
I see that you have imported the other png images of our other tanks that naima has made, will the positions of wheels in both the planck, and pixi coord system be the same? (ideally it should be because that would be a lot easier to code, but that may cause a neeed for a redesign for the sprites)

2025-01-02 13:56 UTC, 3NJDGZ commented on src/core/player.js
> +            gravityScale: 0.5,
why is gravity scale set to 0.5? shouldnt it be set ideally to 1 to accurately simulate real world physics of -9.8ms^(-2) deceleration of gravity? I assume if you do change it to 1 it will mess with the trajectory speed but that is ultimatley my fault in how we are translating from the pixijs coord system to planckjs system and vice versa. Again it relates to:
```javascript
var PixelsPerMeter = 50;					// How many pixels represent 1 meter.
var MetersPerPixel = 1/PixelsPerMeter;		// And the reverse.
``` 
And how we would use the values to translate between the two.

2025-01-02 13:58 UTC, 3NJDGZ commented on src/core/player.js
> +        const ballVFD = {initialVelocity: 10, friction: 0.3, density: 1};
ballVelocityFreqDensity?

2025-01-02 14:02 UTC, 3NJDGZ commented on src/core/player.js
> +            linearVelocity: Vec2(velX, velY * 2),
why is velY multiplied by 2? It should be just be velY no?

2025-01-02 14:02 UTC, 3NJDGZ commented on src/core/player.js
> +        console.log("Shell fired:", this.physicalShell);
redundant log statement (assume it was used for debugging)

2025-01-02 14:22 UTC, 3NJDGZ commented on src/core/player.js
iluihiuhuihiuh

2025-01-02 14:33 UTC, 3NJDGZ requested changes
Looks good, but a few bits need to be changed. After my uni exams, we'll need to focus on changing how we translate from the different coord systems, cus i think i messed it up

2025-01-02 16:13 UTC, Chris33871 commented on src/core/player.js
> +        let [px, py] = [this.playerBody.getPosition().x, this.playerBody.getPosition().y] // x,y position according to planck
I changed the name.

Yeah, planck position for this object is adapted? Not sure I understand what you're getting at

2025-01-02 16:14 UTC, Chris33871 commented on src/core/player.js
> +        this.springBack = this.world.createJoint(
Yes. Motor speed and suspension (will be severely dampened later). I like to see the tanks bounce

2025-01-02 16:16 UTC, Chris33871 commented on src/core/player.js
>          const playerSprite = Sprite.from(this.playerTexture);
Other images don't work. It imports the white background.
The wheels will be fine, as long at they're below the tank it's ok. If we want custom tanks later we can implement them (maybe you want a tank with monster truck wheels. That'll have to be done once we have a selection screen or something)

2025-01-02 16:18 UTC, 3NJDGZ commented on src/core/player.js
> +        let [px, py] = [this.playerBody.getPosition().x, this.playerBody.getPosition().y] // x,y position according to planck
My fault, I mean that when I change the scales for converting from pixi to Planck and vice versa, it'll need to be adapted just to let you know. Cuz I wanna follow how they did it in the demo code if that makes sense?

2025-01-02 16:19 UTC, Chris33871 commented on src/core/player.js
> +        const ballVFD = {initialVelocity: 10, friction: 0.3, density: 1};
Yeah. Even though initial velocity isn't a real parameter lol. Forgot to change that

2025-01-02 16:21 UTC, Chris33871 commented on src/core/player.js
> +            linearVelocity: Vec2(velX, velY * 2),
velY on it's own is too slow

2025-01-02 16:23 UTC, Chris33871 commented on src/core/player.js
> +        let [px, py] = [this.playerBody.getPosition().x, this.playerBody.getPosition().y] // x,y position according to planck
ah ok ok yeah

2025-01-02 21:13 UTC, 3NJDGZ commented on src/core/player.js
> +            gravityScale: 0.5,
bro is articulate

2025-01-02 21:13 UTC, 3NJDGZ commented on src/core/player.js
> +            gravityScale: 0.5,
'creative liberty has been taken'

2025-01-04 14:14 UTC, 3NJDGZ approved these changes
mergeeeeeeee

2025-01-04 14:14 UTC, merged